spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your gmail acount
    password: gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  activemq:
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true