spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your email address
    password: your email password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true